system:
    services:
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:RNsN6N5ZHrOFXHKJus8QdsXxlm13rItxPk6lJFiPRgoXKAUILFAffQ==,iv:klIoLvNw4xbF5y6IXJsTWPyCZNKYfSs0t3DR8L7/yrM=,tag:f9GXXuuEZpn+rEM2hWs5lA==,type:str]
sops:
    age:
        - recipient: age123dsa4ane5583sezln90h5ax8hjyx4c2r5psu6ydxy8k5xtfva6sme6pa0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcVhTbmFzaFBuU1FyR3lp
            TXFGV3ljNkRDbnd0dWJ0MW13bXM4dHp5ZHh3CnNMVFNQSklpZUlyRGwxdWVwQ1hU
            ZmprclRtVzhXZXpicGlrK0xLMGVWdGMKLS0tIEtPWG4ycTZrVlBrc2FzVFNPSi9F
            WlNCMlVod2tiSGpQWlpxZWZKZWZJRncKTyqXp5Vm8BloReiTIbu/IILRW6t3Q98D
            K49rCIZ6E8Uqt3C6P0at54HqnxHADCWMGEe+lI88vIGvDGtbr/FEcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lzhjalfd2vw8xva4va459ey4389wdjh59cwn8rvlf0txagvw6f2qdpt6wp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNjhuTGc4Y3pHRWovZHJO
            ejhOTmFmenZoRTJmYi9JTU5mVHhWU0U2QkhZClFrZkRtUThUY1hiRU1EbUhPbmlW
            QVVYWWdlVG1NazZ1TS9LaHRQdUQ4TjQKLS0tIHpienNxQUtvR1F3VURnallyNmhM
            MHdUbEJweHBWVzB0bXVZYndDUG9pNTAKUyR1+5KfQLSGCJaU8WpDrIfaUTBx6ejn
            RIA3s83orjRh5T3i6nI2zkH8ElUegZq2icN3IBXek2Uq/iFiV/4gkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T00:02:51Z"
    mac: ENC[AES256_GCM,data:a+BWH5COdCqDJo+6TuepUoML1aJiwtvJt+WMs6YQXNtSPhDBF5HhEAnoBvWcwR7ARjtY41U1L7b0qZ6ZhdbtAlIZ9XGvmsYKwHRobqU15ulLPMzt04YZ9l8dBwRB+d2SigW962zrYxuuwuJ8vH/1esgOgZeA9uJGPHVb7WRzkrE=,iv:CsSLIGauXL/CKn84kFBaj4EIMMg5+x1uIFFOVPw5hBo=,tag:0wPxTAGxX8FOg8H61OyoTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
